
import "../../assets/css/styles.css"
import { CreateWikiHeader } from "../Wiki"



function UniverseOrigin() {
    return (
        <div class="Container">
            {CreateWikiHeader()}
            <div className="d-flex flex-column p-5 mb-5 justify-content-center align-items-center">
                <h1 className="mb-3">The Beginning of Everything</h1>
                <p>In the beginning of time, there was nothing but darkness and nothingness. A single, lonely, dimension called Emporea, incredibly imbued with magic and unbelievably unstable, was the center of everything. No elements nor life forms could be found in the prime dimension, which consisted of nothing but pure brutal magic. This raw magic brewed for billions of years until the core of the dimension exploded, propelling its magic at an unimaginable speed and distance in all directions, the trails of its magic leaving pure purple tunnels of magic. In some areas, these tunnels connected to one another, creating a large powerful magical connection and leaving new subsequent dimensions inside of Emporea behind as they kept traveling through their collision. With more tunnels passing through these newborn dimensions and imbuing them with their primal raw magical energy, they inherited the magic of their mother. Some magical trails lasted for centuries, others millennia, but each and every one of them finally found peace and eventually stopped, creating another child dimension where they ended their voyage. Emporea emptied itself of its energy, creating perfect balance in itself. Settled and still immaterial, its children brewed with their own chaos, sometimes bursting and creating permanent connections in the forms of tunnels with their siblings. These tunnels began to flourish by themselves with the help of the magical energy of their parents, each allowing passage in between the two connected dimensions. The result of these connections was an almost magnetic-like field, as some connections would eventually appear and be created in between further dimensions, only to disappear some time after. While the raw magical energy finally came to a rest, these tunnels remained unstable and ever-changing, the more raw energy inside of them, the faster one would travel. The fewer tunnels around it to temper with its magical field, the faster the transfer would feel. These tunnels are now known as the Astral pathways. The process of balancing inside of Emporea finally came to a conclusion when all of its children’s molten energy came to stabilize. As a way of perfecting her craft, she soon began to consume those amongst her children with the weakest energy, creating what is now known as Cataclysms.</p>
                <p>Having developed a subconscious of their own, the children of Emporea fought back against her mother, creating the first elements and sharing them amongst themselves across the Astral passage. Water, air, earth and fire eventually appeared in all of them, their chemistry creating the material of all dimensions. For the first time, there was light and darkness, there was grass and earth, the dimensions were no longer pure magical entities. Still very much vulnerable to the demise that their mother reserved for the weakest amongst them, the children of Emporea all gathered their magical energy together, some even sacrificing the entirety of what they had, and created the prime elementals; the first divinities. Forced to travel across the Astral passage to avoid the demise of their parents, the prime elementals ventured worlds constantly. On a fine sunny day, the prime elementals gathered and gave the name of Uinderal to the universe in which they walked. At long last Emporea finally managed to make the elementals fall to its core, however as she attempted to remove them from her world, she realized that she was unable to consume their energy. Their energy was not magical energy, it was elemental energy. Unable to get rid of the prime elementals by devouring their elemental energy, Emporea created a secluded dimension where she sent the first divinities and made the astral passage’s pathways invisible to the naked eye.</p>
                <p>As Emporea continued to get rid of her weakest creations, the elemental dimension grew more populated as the prime elementals made creations of their own. Centuries passed as they lived peacefully in the society, the elemental dimension growing more crowded and diverse with every passing year. With their growth came their fall. Wanting more area for their children to grow and disagreeing with one another, the prime elementals waged war against each other, forgetting their origins over a disagreement. The prime elementals battled over territory until they managed to shatter the construct of their dimension with too much energy, being absorbed and falling through their world to the ground of Emporea. Furious, the mother of dimensions cast away the prime deities and their children forever away from her, and created the planes of existence.</p>
                <p>Cast away inside of the elemental plane, the prime elementals continued their fight, their children grew ever divided as they began to realize that the planes were large enough for them and that their reason to fight was no longer a cause but rather an old grief. Some elementals continued to fight, swearing allegiance to their parents until the day that they’d die, others began to care for themselves and prioritized their freedom over the ongoing conflict. The elementals began to grow more divided with their methods, some remembering their kin as brothers and sisters and refusing to cause them more harm than they needed to, while others grew greedier and took pleasure in wreaking havoc, destruction and grief on those they once called family. As the divided elementals fell in combat, the outer planes began to welcome their first deities, demons, devils and angels. The worst of them would end in the lower planes while the best of them would end in the higher planes, each one from the lower planes forgetting everything about their old identity with the exception of their desire to vanquish and dominate those from different planes.</p>
                <p>Left to their demise till the end of times, the children of Emporea suffered for millennia as their creation waged war against themselves in the different planes of existence. But the elemental planes and outer planes had an effect that Emporea had never anticipated. Soon, the ground of her children began to turn green, plants grew, fish appeared in their seas, tall mountains rose to pierce the sky, and large forests filled with creatures began to cover their landscapes. Soon, the elves began to appear. Then followed the orcs, the humans, the dwarves and all of the other races. Civilizations began to rise upon their soil, and life began to shine in Uinderal. Emporea, indifferent at first, quickly realized that she wasn’t able to consume the new type of energy and those who fell to her bottom began to harness her magic against her. Terribly annoyed at the result of her own doing, Emporea placed her own raw magical energy inside of the soul of the unfortunate ones who had found a home inside of her domain, creating emporean energy and bringing the first fiends of depth of Uinderal to life. Creatures which were affected by her vicious curse had their memory erased and felt a constant need to track and feed off of life energy, forced to clean Emporea off of the energy she couldn’t get rid of till the end of times. This creation acted as a token of promise to her children that her will to achieve complete balance was inevitable, once more. </p>
                <p>With the last of their subconscious energy, the heirs of Emporea began to infuse the soul energy of some creatures residing inside of them with their own, creating divinian energy, an endless source of energy which would protect them for as long as it remains with them. Humans, elves, dwarves, orcs, creatures of all sorts awoke in some dimensions to find themselves imbued with divine power, they were made gods. Some appeared out of nowhere and were seemingly creating out of nothingness, some ascended and lost their memory, some ascended but remained true to who they were before, these divinities all had their own identity and agendas but were each bonded to their creator for the rest of eternity, the Astral passage becoming inaccessible for any of them. Some walked the ground amongst the creatures residing there while others created their own plane over the dimension in which they resided. The best and worst could be found amongst them and although the children of Emporia wanted nothing but the best, this was their only solution to prevent any Cataclysms from happening. While the strongest of these dimensions managed to assure immortality and eternity to their new divinities, the weakest dimensions failed.</p>
                <p>Emporea found herself greatly penalized by the last sacrifice of her children and gave up on her quest for stability. Instead, she pledged to start all over again from scratch and began to slowly consume all of her children which had failed to create divinian energy. As for the others, she began to patiently wait for the endless sources of energy amongst them to extinguish before sending a cataclysm their way, and letting her fiends of depths take care of the survivors. Although the dimensions are now dormant and their subconscious are no more, their children remain. Across a few dimensions can be found creatures aware of the universe and its past. Following in the footsteps of their ancestors, they have dedicated their life to stopping Emporea, to save Uinderal. </p>
            </div>
        </div>
    );
}

export default UniverseOrigin;